#Mehul Is the name of the person testing this activity

steps:

  # Install npm dependencies

  - name: 'gcr.io/cloud-builders/npm'

    args: ['install']

  # Run tests (if applicable)

  - name: 'gcr.io/cloud-builders/npm'

    args: ['test']

  # Build the Docker image

  - name: 'gcr.io/cloud-builders/docker'

    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-nodejs-app', '.']

  # Push the Docker image to Google Container Registry

  - name: 'gcr.io/cloud-builders/docker'

    args: ['push', 'gcr.io/$PROJECT_ID/sample-nodejs-app']

  # Deploy to Google Cloud Run

  - name: 'gcr.io/cloud-builders/gcloud'

    args:

      - 'run'

      - 'deploy'

      - 'sample-nodejs-app'

      - '--image=gcr.io/$PROJECT_ID/sample-nodejs-app'

      - '--platform=managed'

      - '--region=us-central1'







